/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BilingualText { 'hindi' : string, 'english' : string }
export interface ContactMessage {
  'id' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'id' : string,
  'caption' : BilingualText,
  'image' : ExternalBlob,
}
export interface OrganizationDetails {
  'mission' : BilingualText,
  'logo' : [] | [ExternalBlob],
  'name' : BilingualText,
  'email' : string,
  'address' : BilingualText,
  'facebookLink' : string,
  'phone' : string,
}
export interface Project {
  'id' : string,
  'title' : BilingualText,
  'description' : BilingualText,
  'image' : [] | [ExternalBlob],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'addGalleryImage' : ActorMethod<[GalleryImage], undefined>,
  'addHomepageImage' : ActorMethod<[GalleryImage], undefined>,
  'addProject' : ActorMethod<[Project], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGalleryImage' : ActorMethod<[string], undefined>,
  'deleteHomepageImage' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getAboutUsContent' : ActorMethod<[], BilingualText>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getHomepageImages' : ActorMethod<[], Array<GalleryImage>>,
  'getOrganizationDetails' : ActorMethod<[], OrganizationDetails>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAboutUsContent' : ActorMethod<[BilingualText], undefined>,
  'updateOrganizationDetails' : ActorMethod<[OrganizationDetails], undefined>,
  'updateProject' : ActorMethod<[Project], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];