/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const BilingualText = IDL.Record({
  'hindi' : IDL.Text,
  'english' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'caption' : BilingualText,
  'image' : ExternalBlob,
});
export const MemberType = IDL.Variant({
  'mainMember' : IDL.Null,
  'coreCommittee' : IDL.Null,
  'ordinaryMember' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : IDL.Text,
  'joinDate' : IDL.Text,
  'name' : BilingualText,
  'role' : BilingualText,
  'memberType' : MemberType,
  'photo' : IDL.Opt(ExternalBlob),
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'title' : BilingualText,
  'description' : BilingualText,
  'image' : IDL.Opt(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DonationDetails = IDL.Record({
  'accountNo' : IDL.Text,
  'ifsc' : IDL.Text,
  'description' : BilingualText,
  'bankName' : IDL.Text,
  'upiId' : IDL.Text,
  'accountHolder' : IDL.Text,
});
export const OrganizationDetails = IDL.Record({
  'mission' : BilingualText,
  'logo' : IDL.Opt(ExternalBlob),
  'name' : BilingualText,
  'email' : IDL.Text,
  'address' : BilingualText,
  'facebookLink' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContactMessage' : IDL.Func([ContactMessage], [], []),
  'addGalleryImage' : IDL.Func([IDL.Text, GalleryImage], [], []),
  'addHomepageImage' : IDL.Func([IDL.Text, GalleryImage], [], []),
  'addMember' : IDL.Func([IDL.Text, Member], [], []),
  'addProject' : IDL.Func([IDL.Text, Project], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGalleryImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteHomepageImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteMember' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAboutUsContent' : IDL.Func([], [BilingualText], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactMessage)],
      ['query'],
    ),
  'getCustomDomain' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getDonationDetails' : IDL.Func([], [DonationDetails], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getHomepageImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getOrganizationDetails' : IDL.Func([], [OrganizationDetails], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getSecurityQuestion' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getAdminSecurityQuestionWithoutId' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdminSetup' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCustomDomain' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setupAdmin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateAboutUsContent' : IDL.Func([IDL.Text, BilingualText], [], []),
  'updateDonationDetails' : IDL.Func([IDL.Text, DonationDetails], [], []),
  'updateMember' : IDL.Func([IDL.Text, Member], [], []),
  'updateOrganizationDetails' : IDL.Func(
      [IDL.Text, OrganizationDetails],
      [],
      [],
    ),
  'updateProject' : IDL.Func([IDL.Text, Project], [], []),
  'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'verifySecurityAnswer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'verifySecurityAnswerWithoutId' : IDL.Func([IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const BilingualText = IDL.Record({
    'hindi' : IDL.Text,
    'english' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'caption' : BilingualText,
    'image' : ExternalBlob,
  });
  const MemberType = IDL.Variant({
    'mainMember' : IDL.Null,
    'coreCommittee' : IDL.Null,
    'ordinaryMember' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : IDL.Text,
    'joinDate' : IDL.Text,
    'name' : BilingualText,
    'role' : BilingualText,
    'memberType' : MemberType,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'title' : BilingualText,
    'description' : BilingualText,
    'image' : IDL.Opt(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DonationDetails = IDL.Record({
    'accountNo' : IDL.Text,
    'ifsc' : IDL.Text,
    'description' : BilingualText,
    'bankName' : IDL.Text,
    'upiId' : IDL.Text,
    'accountHolder' : IDL.Text,
  });
  const OrganizationDetails = IDL.Record({
    'mission' : BilingualText,
    'logo' : IDL.Opt(ExternalBlob),
    'name' : BilingualText,
    'email' : IDL.Text,
    'address' : BilingualText,
    'facebookLink' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContactMessage' : IDL.Func([ContactMessage], [], []),
    'addGalleryImage' : IDL.Func([IDL.Text, GalleryImage], [], []),
    'addHomepageImage' : IDL.Func([IDL.Text, GalleryImage], [], []),
    'addMember' : IDL.Func([IDL.Text, Member], [], []),
    'addProject' : IDL.Func([IDL.Text, Project], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGalleryImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteHomepageImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteMember' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAboutUsContent' : IDL.Func([], [BilingualText], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getCustomDomain' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getDonationDetails' : IDL.Func([], [DonationDetails], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getHomepageImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getOrganizationDetails' : IDL.Func([], [OrganizationDetails], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getSecurityQuestion' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getAdminSecurityQuestionWithoutId' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdminSetup' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCustomDomain' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setupAdmin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateAboutUsContent' : IDL.Func([IDL.Text, BilingualText], [], []),
    'updateDonationDetails' : IDL.Func([IDL.Text, DonationDetails], [], []),
    'updateMember' : IDL.Func([IDL.Text, Member], [], []),
    'updateOrganizationDetails' : IDL.Func(
        [IDL.Text, OrganizationDetails],
        [],
        [],
      ),
    'updateProject' : IDL.Func([IDL.Text, Project], [], []),
    'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'verifySecurityAnswer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'verifySecurityAnswerWithoutId' : IDL.Func([IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };