/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BilingualText { 'hindi' : string, 'english' : string }
export interface ContactMessage {
  'id' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface DonationDetails {
  'accountNo' : string,
  'ifsc' : string,
  'description' : BilingualText,
  'bankName' : string,
  'upiId' : string,
  'accountHolder' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'id' : string,
  'caption' : BilingualText,
  'image' : ExternalBlob,
}
export interface Member {
  'id' : string,
  'joinDate' : string,
  'name' : BilingualText,
  'role' : BilingualText,
  'memberType' : MemberType,
  'photo' : [] | [ExternalBlob],
}
export type MemberType = { 'mainMember' : null } |
  { 'coreCommittee' : null } |
  { 'ordinaryMember' : null };
export interface OrganizationDetails {
  'mission' : BilingualText,
  'logo' : [] | [ExternalBlob],
  'name' : BilingualText,
  'email' : string,
  'address' : BilingualText,
  'facebookLink' : string,
  'phone' : string,
}
export interface Project {
  'id' : string,
  'title' : BilingualText,
  'description' : BilingualText,
  'image' : [] | [ExternalBlob],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'addGalleryImage' : ActorMethod<[string, GalleryImage], undefined>,
  'addHomepageImage' : ActorMethod<[string, GalleryImage], undefined>,
  'addMember' : ActorMethod<[string, Member], undefined>,
  'addProject' : ActorMethod<[string, Project], undefined>,
  'adminLogin' : ActorMethod<[string, string], string>,
  'adminLogout' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGalleryImage' : ActorMethod<[string, string], undefined>,
  'deleteHomepageImage' : ActorMethod<[string, string], undefined>,
  'deleteMember' : ActorMethod<[string, string], undefined>,
  'deleteProject' : ActorMethod<[string, string], undefined>,
  'getAboutUsContent' : ActorMethod<[], BilingualText>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessages' : ActorMethod<[string], Array<ContactMessage>>,
  'getCustomDomain' : ActorMethod<[], [] | [string]>,
  'getDonationDetails' : ActorMethod<[], DonationDetails>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getHomepageImages' : ActorMethod<[], Array<GalleryImage>>,
  'getMembers' : ActorMethod<[], Array<Member>>,
  'getOrganizationDetails' : ActorMethod<[], OrganizationDetails>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getSecurityQuestion' : ActorMethod<[string], string>,
  'getAdminSecurityQuestionWithoutId' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdminSetup' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetAdminPassword' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCustomDomain' : ActorMethod<[string, string], undefined>,
  'setupAdmin' : ActorMethod<[string, string, string, string], undefined>,
  'updateAboutUsContent' : ActorMethod<[string, BilingualText], undefined>,
  'updateDonationDetails' : ActorMethod<[string, DonationDetails], undefined>,
  'updateMember' : ActorMethod<[string, Member], undefined>,
  'updateOrganizationDetails' : ActorMethod<
    [string, OrganizationDetails],
    undefined
  >,
  'updateProject' : ActorMethod<[string, Project], undefined>,
  'validateAdminSession' : ActorMethod<[string], boolean>,
  'verifySecurityAnswer' : ActorMethod<[string, string], string>,
  'verifySecurityAnswerWithoutId' : ActorMethod<[string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];